### ISSUE TITLE
pre_start deferred not waited before calling receive()

### ISSUE THREAD

**Issue by mkmik** [erikkaplun/spinoff#3]
``` python
from spinoff.actor import Actor
from txcoroutine import coroutine
from spinoff.util.async import sleep
from spinoff.util.logging import dbg


class SomeActor(Actor):

    @coroutine
    def pre_start(self):
        yield sleep(2.0)
        self.val = 1

    def receive(self, msg):
        dbg(self.val)

class Test(Actor):
    def pre_start(self):
        a = self.spawn(SomeActor)
        a << 'test'
```

``` sh
(spinoff)marko@ributtalo $ ./twistd-autoreload.py --nodaemon startnode --actor prestart.Test 
2012-11-21 15:44:25+0100 [-] Log opened.
2012-11-21 15:44:25+0100 [-] twistd 12.2.0 (/home/marko/.virtualenvs/spinoff/bin/python 2.7.3) starting up.
2012-11-21 15:44:25+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
14:44:25 7457 log    events.py:129 Events    in log: Running: prestart.Test 
14:44:25 7457 log    events.py:129 Events    in log: No remoting requested; specify `--remoting/-r <nodeid>` (nodeid=host:port) to set up remoting 
14:44:25 7457 log    events.py:129 Events    in log: Spawned </test$1> 
14:44:25 7457 fail   _actor.py:1215 cell:SomeActor@/test$1/someactor$1  N X  in failure report 

 Traceback (most recent call last):
  File "/home/marko/Projects/spinoff/spinoff/actor/_actor.py", line 918, in _process_messages
    yield self._process_one_message(message)
  File "/home/marko/Projects/spinoff/spinoff/actor/_actor.py", line 967, in _process_one_message
    self._ongoing = receive(message)
  File "/home/marko/Projects/spinoff/prestart.py", line 15, in receive
    dbg(self.val)
AttributeError: 'SomeActor' object has no attribute 'val'

14:44:25 7457 fail   events.py:129 Events    in log: Error(</test$1/someactor$1>, AttributeError("'SomeActor' object has no attribute 'val'",), <traceback object at 0x34d52d8>) 
14:44:25 7457 debug  _actor.py:1030 cell:Test@/test$1  X  in sup: AttributeError("'SomeActor' object has no attribute 'val'",) ← </test$1/someactor$1>      
14:44:25 7457 debug  _actor.py:1043 cell:Test@/test$1  X  in sup: → Restart → </test$1/someactor$1> 
```

**Comment by erikkaplun** [comment]
Fixed in 8e96616
