### ISSUE TITLE
Closing null connection

### ISSUE THREAD

**Issue by mkmik** [erikkaplun/spinoff#5]
```
nhandled Error
Traceback (most recent call last):
  File "/home/marko/.buildout-eggs/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/marko/.buildout-eggs/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/marko/.buildout-eggs/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 626, in _doReadOrWrite
    why = selectable.doRead()
  File "build/bdist.linux-x86_64/egg/txzmq/connection.py", line 227, in doRead

--- <exception caught here> ---
  File "/home/marko/.buildout-eggs/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/marko/.buildout-eggs/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/marko/.buildout-eggs/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/marko/.buildout-eggs/Twisted-12.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "build/bdist.linux-x86_64/egg/txzmq/connection.py", line 296, in messageReceived

  File "/home/marko/.buildout-eggs/spinoff-0.5.5-py2.7.egg/spinoff/actor/remoting.py", line 213, in _got_message
    conn.close()
exceptions.AttributeError: 'NoneType' object has no attribute 'close'

```

I noticed this issue. Sorry I don't have time to reproduce it cleanly. 
My code tries to send messages to a remote actor which is down.

It happens after ~11 minutes that the code is running and printing DeadLetters.

**Comment by mkmik** [comment]
Hmm, no sorry, it doesn't happen by itself.

I have another remote actor which connects (looks up this actor) and waits for a reply.

This actor doesn't reply and the sender dies after a Timeout. After the client dying, this node logs this error.

**Comment by erikkaplun** [comment]
It's already been fixed in master.
